"""increase prescription_number length

Revision ID: 3245c10bb93e
Revises: b8c3d4e5f6g7
Create Date: 2026-02-27 16:40:21.148637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3245c10bb93e'
down_revision = 'b8c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_appointment_collision', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('prescription_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('prescription_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('idx_appointment_collision')

    # ### end Alembic commands ###
