"""Extend appointment_number length to 50

Revision ID: b8c3d4e5f6g7
Revises: a7b2c3d4e5f6
Create Date: 2026-02-14 19:42:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c3d4e5f6g7'
down_revision = 'a7b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_number',
               existing_type=sa.String(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_number',
               existing_type=sa.String(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
